# Generated by Django 5.1 on 2024-08-21 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
